### ISSUE TITLE
Attending some and skipping some classes of the course

### ISSUE THREAD

**Issue by accakks** [CodeDocsJECRC/CD101#2]
For example, if I know HTML and CSS and wish to attend from only Js, or any other similar case, would that be okay? (attending sessions/classes of my choice) or it would be a whole course thing?

**Comment by maddhruv** [comment]
We just have to show the department about the attendance of the students and in the end a detailed report of how students were engaged in the course, what was the outcome of conducting the course and such other things.
We could allow you to attend only the interested classes.

**Comment by maddhruv** [comment]
Any student can attend any class but he should have the knowledge of what was taught in the previous classes.

**Comment by maddhruv** [comment]
If there will be any possibility of certification then surely the certificates will be for those who have attended almost all the lectures and sessions

**Comment by accakks** [comment]
Okay Thanks, Well now that the classes are before bus timings, attending all would be even better! Thanks for the info!
